steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [ "build", "-t", "gcr.io/$PROJECT_ID/github.com/rjial/ngipen-frontend:$COMMIT_SHA", "." ]

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker:latest'
    args:
      - push
      - 'gcr.io/$PROJECT_ID/github.com/rjial/ngipen-frontend:$COMMIT_SHA'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - '-c'
      - |
        gcloud run deploy ngipen-frontend \
          --image gcr.io/$PROJECT_ID/github.com/rjial/ngipen-frontend:$COMMIT_SHA \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated
